title = "Example GoMux Config"

[config]
session = "SessionName"
project = "~/projects/myproject"

[windows]

[windows.editor]
cmd = "vim ."

[windows.docker]
cmd = "docker compose up"

[windows.database]
cmd = "psql"

[windows.server]
cmd = "go run cmd/main.go"

