title = "Example GoMux Config"

[config]
session = "SessionName"
project = "~/Developer/gomux"
start_index = 0

[windows]

[windows.editor]
name = "editor"
cmd = "vim ."

[windows.htop]
name = "htop"
cmd = "htop"
