title = "Example GoMux Config"

[config]
session = "SessionName"
project = "~/Developer/gomux"
start_index = 0

[windows]

[windows.editor]
name = "editor"
cmd = "vim ."

[windows.docker]
name = "docker"
cmd = "docker compose up"

[windows.database]
name = "database"
cmd = "psql"

[windows.server]
name = "server"
cmd = "go run cmd/main.go"
